name: Enviar relatório meteorológico

on:
  schedule:
    - cron: '0 3 * * *'  
  workflow_dispatch:     

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar navegadores do Playwright
        run: playwright install --with-deps

      - name: Executar script principal
        env:
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
          SENHA_APP: ${{ secrets.SENHA_APP }}
          LATITUDE: ${{ secrets.LATITUDE }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
        run: python src/weather_report/main.py
