name: Enviar relatório meteorológico

on:
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    container:
      image: mcr.microsoft.com/playwright/python:v1.54.0-jammy

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Atualizar pip e instalar dependências do projeto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script principal
        env:
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
          SENHA_APP: ${{ secrets.SENHA_APP }}
          LATITUDE: ${{ secrets.LATITUDE }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
        run: python src/weather_report/main.py
